server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.5.15:1111 #换成nginx的1111端口，做集群

management:
  endpoints:
    web:
      exposure:
        include: '*'