server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    # 对8001端口的两个controller方法进行路由，相当于网关挡在实际访问地址的前面
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由
            - After=2020-08-01T15:01:31.215+08:00[Asia/Shanghai] # 在这个时间过后的服务才可以正常访问
#            - Cookie=username,wang  # 带上cookie一起访问
#            - Header=X-Request-Id,\d+ # 请求头要有X-Request-Id属性并且值为正数的正则表达式

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由


eureka:
  instance:
    hostname: cloud-gateway-service
  client: # 服务提供者provide注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka